# -*- coding: utf-8 -*-
"""16MI31022BhendeDhawal_Lab8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GbKYigrkTv_1FZztw_aAOgd0VCNrIXHJ
"""

q = []
for i in range(5):
    q.append([-25-5*i,300+5*i])
H = 100                                             #Height of slope
c = 7                                         #Cohesion
Y = 21                                                  #UnitweightofSoil
n = 22                                            #last two digit of roll number is 22
F = []
Rlist=[]
XClist=[]
mid=[]
angle=[]

for k in q:
    R = pow(k[0]*k[0] + k[1]*k[1],0.5)                                       #Calculating the radius of slip circle
    Xm =k[0] - pow(R*R-(H-k[1])*(H-k[1]),0.5)                           #Calculating the coordinates of extreme point (xm,H)
    w = (0-Xm)/n                                                               #Finding the width of slices
    Xp = -H
    FoS = 1
    err = 1
    z = 0
    b = 0
    while abs(err)>0.001:
        for i in range(0,22):
            Xmid = (Xm + w/2) + i*w
            Ymid = k[1] - pow(R*R-(Xmid-k[0])*(Xmid-k[0]),0.5)                         #Calculating the coordinates of midpoints: xmid, ymid  of slice
            if Xmid <= Xp:
                h = H - Ymid
            if Xmid > Xp:
                h = abs(Xmid) - Ymid                                                              #Finding height of slice for two condition
            m = (k[0]-Xmid)/(k[1]-Ymid)
            wt = h*w*Y                                                  #Weight of slice calculation
            sec_i = pow(m*m+1,0.5)
            sin_i = pow(1/(1+1/m*m),0.5)
            z = z + ((c + Y*h*0.577)*w*sec_i)/(1 + (m/FoS))
            b = b + wt*sin_i
        err = z/b - FoS
        FoS = z/b
    F.append(FoS)
    Rlist.append(R)
    XClist.append(Xm)
    mid.append((Xmid, Ymid))
    angle.append(sin_i)                                                           #FOS Calculation

fmin=F[0]
qmin=q[0]
rmin=Rlist[0]
Xemin=XClist[0]
midmin=mid[0]
angmin=angle[0]
for i in range(0, len(F)):
  if F[i]<fmin:
    fmin=F[i]
    qmin=q[0]
    rmin=R[i]
    Xemin=XClist[i]
    midmin=mid[i]
    angmin=angle[i]

print("Minimum FOS: ", "%.3f"%fmin)
print("\nCorrspondong cordinate in search box", qmin)
print("\nRadius of slip circle: ", "%.3f"%rmin)
print("\n Coordinates of extreme point: (", "%.3f"%Xemin, H, ")")
print("\n Mid points of slice: ", midmin)
print("\n Angle of inclination of slice: sin^-1(", sin_i, ")" )

